services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: movie_streaming
    volumes:
      # This volume persists your data across container restarts
      - mongodb_data:/data/db
      # Copy seed data to container
      - ./seed/magic-stream-seed-data:/seed
      # Run initialization script
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: unless-stopped

# Declares the volume for data persistence
volumes:
  mongodb_data:
